{application,mants,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,lager,cowboy]},
              {mod,{mants_app,[]}},
              {env,[]},
              {modules,[mants_app,mants_defs,mants_sup,world_data_handler,
                        ws1_handler,ws_handler]}]}.
